### ISSUE TITLE
Added hex option

### ISSUE THREAD

**Issue by tak-tsuchiya** [ssol-smartcs/ansible-collections#25]
# smartcs_tty_command モジュール仕様
- sendchar オプションのサブオプションに ＿HEX＿:hexsを追加
- recvcharを待たない
- CLIがttysendのみ対応の為
- console logに制御コードが混ざり受信文字列待ちが動作しない可能性がある為受信文字列を待たないttysendのみに対応した（v3.0)
- 指定できるHEXは00～7F。最大64文字 (CLIと同じ仕様)。仕様外の場合、playbookを実行せずエラーとする
- CLIを実行してエラーでも良いが、エラーに気が付くのが遅くなる
- 現モジュールはエラーチェックはできるだけモジュール側で実行し、早めにエラーに気が付く思想で作成しているとの事だったので今回も引き継ぐ事にした
- モジュールの作りとして、playbookを全てチェックし、エラーなら実行せず終了。OKならssh接続してCLIを実行する作りになっている
- 送信文字列の最後に改行コードは送信しない。改行コードを送信したい場合 hexで指定する事(CLIと同じ）
- sendchar のサブオプション＿NOWAIT＿:sec と併用可。未指定の場合 hex文字列送信後 default 1秒wait。secの指定範囲は現仕様と同じ。1～7200sec

## 使用例
- date\n を hexで送る場合のplaybook
```
- name: Execute IOS show version command from console using SmartCS
  hosts: smartcs
  gather_facts: no

  vars:
    - ansible_connection: ansible.netcommon.network_cli
    - ansible_network_os: seiko.smartcs.smartcs
    #- ansible_user: smartcs-ansible
    #- ansible_password: password
    - ansible_user: ext
    - ansible_password: ext
    - ansible_command_timeout: 600

  tasks:
  - name: Login to Network Device via Console Server SmartCS and execute "show version"
    seiko.smartcs.smartcs_tty_command:
      tty: 1
      cmd_timeout: 5
      recvchar:
        - 'Username: '
        - 'Password: '
        - '_1>'
        - '_1#'
        - 'Press RETURN to get started.'
      sendchar:
        - '__NL__'
        - 'ne'
        - 'network'
        - 'enable'
        - 'network'
        - 'terminal length 0'
        - 'show version'
        - '__HEX__: 68 65 6C 70 0a' ★これ
        - '__HEX__: 68 65 6C 70 0a __NOWAIT__:5' ★これ
        - 'exit'
 ```     

- エラー例：文字数が64より多い場合
```
            "sendchar": [
                "__HEX__: 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 0a",
                "__HEX__: 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 0a 0a",
                "__HEX__: 64 61 74 65 0a __NOWAIT__:10",
                "__HEX__: 64 61 74 65 0a __NOWAIT__",
                "show version"
            ],
            "src": null,
            "tty": "32",
            "ttycmd_debug": "off"
        }
    },
    "msg": "invalid sendchar __HEX__: 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 64 61 74 65 0a 0a 0a."
}
...ignoring

PLAY RECAP *********************************************************************
NS2250-32_05_v4            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

- エラー例：文字種が00～7F以外の場合
```
            "sendchar": [
                "__HEX__: 64 61 74 65 0a",
                "__HEX__: 64 61 74 65 80",
                "__HEX__: 64 61 74 65 0a __NOWAIT__:10",
                "__HEX__: 64 61 74 65 0a __NOWAIT__",
                "show version"
            ],
            "src": null,
            "tty": "32",
            "ttycmd_debug": "off"
        }
    },
    "msg": "invalid sendchar __HEX__: 64 61 74 65 80."
}
```
